console.log('--- STARTING DEBUG_SERVER.JS ---');
console.log('require express...');
const express = require('express');
console.log('require cors...');
const cors = require('cors');
console.log('require helmet...');
const helmet = require('helmet');
console.log('require hpp...');
const hpp = require('hpp');
console.log('require morgan...');
const morgan = require('morgan');
console.log('require rate-limit...');
const rateLimit = require('express-rate-limit');
console.log('require path...');
const path = require('path');
console.log('require http...');
const http = require('http');
console.log('require socket.io...');
const { Server } = require('socket.io');
console.log('require fs...');
const fs = require('fs');
console.log('SUCCESS');
